Id: Tiled.Tiled
Publisher: Tiled
Name: Tiled
AppMoniker: tiled
Version: 1.4.3
License: GPL 2.0 or later
Tags: "tiled, tilemap, editor, foss, cross-platform, gamedev, graphics"
FileExtensions: "tmx, tsx"
Description: Free, easy to use and flexible level editor.
Homepage: https://www.mapeditor.org/
InstallerType: msi
Installers:
  - Arch: x64
    Url: https://github.com/bjorn/tiled/releases/download/v1.4.3/Tiled-1.4.3-win64.msi
    Sha256: 99bb2490c2e3480039cda79b270e258e55fb3cf624164734b69333267dfbda7b
# ManifestVersion: 0.1.0
